version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FMP_API_KEY=YOUR_FMP_API_KEY  # Replace with your actual API key
    volumes:
      - .:/app
    restart: unless-stopped
